---

resources:
- name: concourse-app
  type: git
  source:
    uri: https://github.com/italolelis/concourse-tutorial

jobs:
- name: unit-test
  serial: true
  plan:
  - get: concourse-app
    trigger: true

  - task: unit test
    file: concourse-app/ci/tasks/unit-tests.yml
